[package]
name = "galactic-wars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = [ ]
debug = [ "bevy-inspector-egui" ]

[dependencies]
bevy = "0.7"
bevy-inspector-egui = { version = "0.10", optional = true }
bevy_text_mesh = "0.2.0"
bevy_rapier3d = { version = "0.14.1", features = ["debug-render","simd-stable", "wasm-bindgen"]}